### ISSUE TITLE
image_guided training [unexpected keyword argument 'head_mask']

### ISSUE THREAD

**Issue by moured** [mitvis/vistext#2]
First of all, thanks for this great work!

I was trying to train with **image_guided, scene_graph and t5 options**. With the following command:

`bash run.sh -c image_guided -b 4 -e 50 -g 4 -i scenegraph -m t5 -s 10 --prefix_tuning`

 But I keep getting the following error  from the modeling_t5.py :

`TypeError: forward() got an unexpected keyword argument 'head_mask'
`

**Comment by versipellis** [comment]
Hey @moured - apologies for the delay on getting back to you on this. Did you manage to resolve the error?

**Comment by moured** [comment]
> Hey @moured - apologies for the delay on getting back to you on this. Did you manage to resolve the error?

Thanks for the replay. Yes, it was a mismatch with the Torch and cuda version.
