### ISSUE TITLE
How to convert datatable to dataframe or other forms which can more clearly reflect the chart?

### ISSUE THREAD

**Issue by FanqingM** [mitvis/vistext#3]
Hello, It is a great work. However I have some question and wich your reply.
After I download the data (just use the script in your repo), I get table str just as:
"datatable": "Worldwide number of Michelin 's full-time employees from 2006 to 2019 <s> Year Number of employees Dec 31, 2005 123975 Dec 31, 2006 121356 Dec 31, 2007 117565 Dec 31, 2008 110300 Dec 31, 2009 102700 Dec 31, 2010 105100 Dec 31, 2011 107300 Dec 31, 2012 105700 Dec 31, 2013 106700 Dec 31, 2014 105800 Dec 31, 2015 105700 Dec 31, 2016 107800 Dec 31, 2017 111100 Dec 31, 2018 121300",
I wonder if there have any clearly format for me to convert it to dataframe?

**Comment by versipellis** [comment]
Hi @FanqingM - thanks for your kind words and interest in VisText! We provide the data in the format we use as input into our models, in this case, it's in the linearized data table form (see Section 3, and figures 1 and 2 in our paper).
