### ISSUE TITLE
Prompt used in vistext

### ISSUE THREAD

**Issue by Road2Redemption** [mitvis/vistext#4]
Hi! I am wondering what prompts you are using in prediction, I can't find them in the folders.

**Comment by aboggust** [comment]
Hello! Thanks for your interest in VisText!

We used the prompt `translate chart to {semantic level}:  `. This comes out to:
* Full caption generation: `translate chart to L1L2L3:  `
* Prefix tuning L1 generation: `translate chart to L1:  `
* Prefix tuning L2/L3 generation: `translate chart to L2L3:  `

This is currently listed in `code/image_guided/chart_caption_data.py`, but I will also add it to the README. 

Thanks for pointing this out, and let me know if you have any other questions!

**Comment by Road2Redemption** [comment]
Thank you for your explanation!
