### ISSUE TITLE
How to create a scene-graph

### ISSUE THREAD

**Issue by SuwonPabby** [mitvis/vistext#7]
Hello, I was deeply impressed by your paper.

However, I have a question. 
I couldn't find the method for generating a scene graph in your repository.

If it doesn't pose a security issue, could you please share that method with me?

**Comment by aboggust** [comment]
Hello @SuwonPabby --- thanks for your interest in VisText!

Our dataset processing script includes our scene graph extraction process and can be found in [`dataset_generation.ipynb`](https://github.com/mitvis/vistext/blob/main/code/dataset_generation.ipynb). We generate the scene graph for each chart using the [Vega-Lite API](https://github.com/vega/vega/tree/main/packages/vega-scenegraph). 

The scene graphs for each of the VisText charts can be [downloaded here](https://vis.csail.mit.edu/vistext/).

**Comment by SuwonPabby** [comment]
Thank you for your kind guidance! Thanks to you, I've figured out how to flatten a given Full SceneGraph into a Compressed SceneGraph using the `utils_gen.parse_all_sg(read_sg)` function.

However, I'm curious about how you obtained the Full Scene-Graph when drawing charts with VegaLite.
It seems that the code only includes the part where the Full SceneGraph is retrieved from a saved path and not includes the part about making Full SceneGraph. (or maybe I just haven't found it due to my lack of expertise 🥲). 
I'm interested in learning how the Full SceneGraph was acquired!

I'm very grateful for your help; it has allowed me to grow significantly. Thank you!

**Comment by SuwonPabby** [comment]
Thanks to the answers you provided, I was able to understand it accurately. 
Thank you for your response! Have a happy day!
